version: '3'

services:
  portainer:
    image: portainer/portainer
    container_name: "portainer-app"
    restart: always
    ports:
      - "9000:9000"    
    command: -H unix:///var/run/docker.sock
    networks:
      - local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/portainer:/data

  watchtower:
    image: v2tec/watchtower
    container_name: "portainer-watchtower"
    restart: always
    command: --cleanup portainer-app portainer-watchtower
    networks:
      - local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  local:
    driver: bridge
